# tell Travis we need super user permissions
sudo: required
# tell Travis what services we need to use
services:
  - docker
# tell Travis what to do before deploying/installing/testing/etc
before_install:
  - docker build -t 1nc0v3nant/docked-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true 1nc0v3nant/docked-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "Dockerfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-646349097775"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY